// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOT1msccxVydwBjsHfC3FRw4C6yQW0xk',
    appId: '1:605555487895:web:57df8f020443e6f34b25d2',
    messagingSenderId: '605555487895',
    projectId: 'push-notifications-fireb-a8ddf',
    authDomain: 'push-notifications-fireb-a8ddf.firebaseapp.com',
    storageBucket: 'push-notifications-fireb-a8ddf.firebasestorage.app',
    measurementId: 'G-WKKRMMQ22N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5BYj8Pe8y3i_DLOhMR97I35TrKlpUMHI',
    appId: '1:605555487895:android:eb3138102161e4b74b25d2',
    messagingSenderId: '605555487895',
    projectId: 'push-notifications-fireb-a8ddf',
    storageBucket: 'push-notifications-fireb-a8ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcpi5XJOGa0gtcwc642GNRsA7IS0zcGuw',
    appId: '1:605555487895:ios:face2b101d6dc7484b25d2',
    messagingSenderId: '605555487895',
    projectId: 'push-notifications-fireb-a8ddf',
    storageBucket: 'push-notifications-fireb-a8ddf.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcpi5XJOGa0gtcwc642GNRsA7IS0zcGuw',
    appId: '1:605555487895:ios:face2b101d6dc7484b25d2',
    messagingSenderId: '605555487895',
    projectId: 'push-notifications-fireb-a8ddf',
    storageBucket: 'push-notifications-fireb-a8ddf.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqOT1msccxVydwBjsHfC3FRw4C6yQW0xk',
    appId: '1:605555487895:web:d7509951b27a29ca4b25d2',
    messagingSenderId: '605555487895',
    projectId: 'push-notifications-fireb-a8ddf',
    authDomain: 'push-notifications-fireb-a8ddf.firebaseapp.com',
    storageBucket: 'push-notifications-fireb-a8ddf.firebasestorage.app',
    measurementId: 'G-1FMDM200XJ',
  );
}
